/** Common vehicle engine configurations for the admin vehicle form. */
export const ENGINE_OPTIONS = [
  "I3",
  "I4",
  "Turbo I4",
  "I5",
  "I6",
  "Turbo I6",
  "Twin-Turbo I6",
  "V6",
  "Turbo V6",
  "Twin-Turbo V6",
  "V8",
  "Supercharged V8",
  "Twin-Turbo V8",
  "V10",
  "V12",
  "W12",
  "Flat-4",
  "Flat-6",
  "Diesel I4",
  "Diesel V6",
  "Diesel V8",
  "Hybrid",
  "Plug-in Hybrid",
  "Mild Hybrid",
  "Electric",
  "Rotary",
  "Other",
] as const;
